### ISSUE TITLE
No route, document, custom route or redirect is matching the request

### ISSUE THREAD

**Issue by josh-palan** [oleksandrmakhno/api-bridge-magento#1]
I'm getting this error message constantly. I'm not exactly sure where the request is coming from.

[Thu Jul 21 16:32:20 2016] [hphp] [9202:7f79a2bff700:16901:000001] [] \nFatal error: Uncaught exception 'Zend_Controller_Router_Exception' with message 'No route, document, custom route or redirect is matching the request: /ApiBridgeMagento/static/js/admin.js?_dc=1469136738 | \nSpecific ERROR: No route matched the request' in /var/www/pimcore/pimcore/lib/Pimcore.php:266\nStack trace:\n#0 /var/www/pimcore/index.php(18): Pimcore::run()\n#1 {main}

**Comment by oleksandrmakhno** [comment]
hi Joshua, 
1. in which pimcore version you are facing this error? 
2. we don't have file static/js/admin.js in this pimcore plugin which is requested in your case, for the first look I may presume pimcore may ask for that file since a new version 

I suggest try adding that file, or just check requested files list for the plugin in your pimcore version

**Comment by josh-palan** [comment]
I figured it out! Looks like the plugin.xml had info in a node it shouldn't. More specifically,

```
<pluginJsPaths>
            <path>/ApiBridgeMagento/static/js/admin.js</path>
</pluginJsPaths>
```

My guess is either I or Pimcore accidentally added that in there when it shouldn't be. Thanks for the help!

**Comment by oleksandrmakhno** [comment]
perfect, good catch Joshua, 
I've just checked, we have admin.js in plugin xml configuration, but not the file itself, 
thank you
